id = "penumbra"
name = "Penumbra"
version = "0.1.1"
schema_version = 1
authors = ["Josef Bisits <jbisits@gmail.com>"]
description = "Penumbra light and dark colour themes"
repository = "https://github.com/jbisits/penumbra-zed"
